### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by Ekumfer5** [davidalger/homebrew-warden#1] opened 2020-11-19 15:10 UTC
Cloning into '/home/linuxbrew/Homebrew/Library/Taps/davidalger/homebrew-warden'...
fatal: unable to access 'https://github.com/davidalger/homebrew-warden/': Could not resolve hosts: github.com
error: failure while executing; 'git clone https://github.com/davidalger/homebrew-warden /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/davidalger/Homebrew-warden' exited with 128.

I get this error message, and I can reach the webpage from a web browser

**Comment by davidalger** [comment] 2020-11-19 19:37
Duplicate of davidalger/warden#266

**Closed as completed by davidalger** 2020-11-19 19:37 UTC
